# Generated by Django 2.2.5 on 2019-09-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.PositiveSmallIntegerField(db_column='yeer', default=2019)),
                ('Week', models.CharField(db_column='weekno', default='Week 38', max_length=20, null=True)),
                ('Month', models.CharField(db_column='menth', default='September', max_length=100)),
                ('Date', models.DateField(db_column='dete', default='2019-09-20')),
                ('Shift', models.TextField(blank=True, db_column='shyft', default='EMEA')),
                ('Day_Of_Week', models.TextField(db_column='dayofweek', default='Weekday')),
                ('Start_Time', models.CharField(db_column='stime', max_length=8, null=True)),
                ('Responded_Time', models.CharField(db_column='rtime', max_length=8, null=True)),
                ('Time_spent', models.CharField(db_column='wtime', max_length=8, null=True)),
                ('Responsible_Team', models.CharField(db_column='respteam', default='Please select', max_length=100, null=True)),
                ('False_Alarm', models.TextField(db_column='falsealarm', default='No')),
                ('Incident_Type', models.CharField(db_column='itype', default='Please select', max_length=100, null=True)),
                ('Priority', models.CharField(db_column='priority', default='None', max_length=10)),
                ('General_Health_Check', models.CharField(blank=True, db_column='ghcname', default='NA', max_length=100, null=True)),
                ('Alert', models.CharField(blank=True, db_column='alertname', default='NA', max_length=100, null=True)),
                ('Task', models.CharField(blank=True, db_column='taskname', default='NA', max_length=100, null=True)),
                ('If_Others_Please_Specify', models.CharField(blank=True, db_column='others', default='NA', max_length=100)),
                ('Description', models.TextField(db_column='descrp', null=True)),
                ('Environment', models.CharField(db_column='env', default='Please select', max_length=100, null=True)),
                ('Host_Type', models.CharField(db_column='hostype', default='Please select', max_length=100, null=True)),
                ('Host_Name', models.CharField(db_column='hostname', max_length=100, null=True)),
                ('Source_of_Alert', models.CharField(db_column='source', default='Please select', max_length=100, null=True)),
                ('Mode_of_Alert', models.TextField(db_column='mode', default='Manual')),
                ('NOC_Engineer', models.CharField(db_column='engineer', default='Please select', max_length=100, null=True)),
                ('Remediation', models.TextField(blank=True, db_column='remediation', default='NA', null=True)),
                ('Escalated', models.CharField(db_column='escalated', default='No', max_length=100)),
                ('Escalated_Reason', models.CharField(blank=True, db_column='escreason', default='NA', max_length=100, null=True)),
                ('Status', models.CharField(blank=True, db_column='status', default='Resolved', max_length=100, null=True)),
                ('Escalated_to', models.CharField(blank=True, db_column='escalatedto', default='NA', max_length=100, null=True)),
                ('Resolved_by_Team', models.CharField(db_column='resolvedteam', default='Please select', max_length=100, null=True)),
                ('Resolved_by_Engineer', models.CharField(db_column='resolvedby', default='noc', max_length=30)),
                ('Resolution', models.TextField(db_column='resolution', null=True)),
                ('Comments', models.TextField(db_column='comments', null=True)),
            ],
        ),
    ]
