# Generated by Django 2.2.5 on 2019-09-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Alert',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Day_Of_Week',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Environment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Escalated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Escalated_Reason',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Escalated_to',
        ),
        migrations.RemoveField(
            model_name='post',
            name='False_Alarm',
        ),
        migrations.RemoveField(
            model_name='post',
            name='General_Health_Check',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Host_Name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Host_Type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='If_Others_Please_Specify',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Incident_Type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Mode_of_Alert',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Month',
        ),
        migrations.RemoveField(
            model_name='post',
            name='NOC_Engineer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Remediation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Resolution',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Resolved_by_Engineer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Resolved_by_Team',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Responded_Time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Responsible_Team',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Shift',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Source_of_Alert',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Start_Time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Time_spent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Year',
        ),
        migrations.AddField(
            model_name='post',
            name='ACCOUNT',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='accnt', default=1, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ACCOUNT_NUMBER',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='accnum', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='A_SITE_ADDRESS',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], db_column='siteaddr', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='CLASSIC_SITE_ID',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], db_column='classiteid', default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='CONTROL_CATEGORY',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='ctcat', default=1, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='CONTROL_REVENUE',
            field=models.TextField(choices=[('1', '1'), ('2', '2')], db_column='ctrlrevenue', default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='COUNTRY',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='ctry', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='GROUP_NAME',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='gname', default=1, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='INVOICE_NUMBER',
            field=models.TextField(choices=[('1', '1'), ('2', '2')], db_column='invcnum', default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='PRODUCT',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], db_column='prdchoices', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='SERVICE_CATEGORY',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], db_column='servcat', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='SERVICE_PERIOD',
            field=models.TextField(choices=[('1', '1'), ('2', '2')], db_column='servprd', default=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='SUPPLIER_BAN_1',
            field=models.TextField(choices=[('1', '1'), ('2', '2')], db_column='sprban1', default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='SUPPLIER_BAN_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='sprban2', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='SUPPLIER_CIRCUIT_ID_1',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='sprcid1', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='SUPPLIER_CIRCUIT_ID_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='sprcid2', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='SUPPLIER_NAME',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='spprnme', default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='USF_CODE',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], db_column='usfcde', default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Priority',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
